name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: SSH Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        # Using appleboy/ssh-action to run remote commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: administrator
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |

            # Where your app lives on the server
            APP_DIR=/var/www/Geo-Ai
            PM2_NAME=Geo-Ai
            VENV_PIP="$APP_DIR/venv/bin/pip"
            VENV_PY="$APP_DIR/venv/bin/python"
            GUNICORN_BIN="$APP_DIR/venv/bin/gunicorn"

            # cd to the main repository
            cd "$APP_DIR"
            echo "=== Pull latest code ==="
            git pull origin main

            echo "=== Install Python dependencies (if changed) ==="
            source venv/bin/activate
            pip install -r requirements.txt

            echo "=== Restart PM2 process if exists, otherwise start it ==="
            # Try graceful reload/restart; if PM2 doesn't know the app, start it with gunicorn
            if pm2 list | grep -q "$PM2_NAME"; then
              pm2 reload "$PM2_NAME" || pm2 restart "$PM2_NAME"
            else
              pm2 start gunicorn --name "$PM2_NAME" --interpreter=none -- \
              -w 4 -k uvicorn.workers.UvicornWorker main:app --bind 209.209.40.144:8000

            fi

            echo "=== Save PM2 process list and show status ==="
            pm2 save

