name: 🚀 Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: administrator
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/Geo-Ai
            git pull origin main
            source venv/bin/activate
            pip3 install -r requirements.txt
            sudo systemctl daemon-reload
            sudo systemctl restart geoai
