name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH Deploy to VPS
    runs-on: ubuntu-latest
    outputs: 
    status: ${{ job.status }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        # Using appleboy/ssh-action to run remote commands
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: administrator
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            # Where your app lives on the server
            APP_DIR=/var/www/python-api
            PM2_NAME=python-api
            VENV_PIP="$APP_DIR/venv/bin/pip"
            VENV_PY="$APP_DIR/venv/bin/python"
            GUNICORN_BIN="$APP_DIR/venv/bin/gunicorn"

            echo "=== Pull latest code ==="
            # Ensure branch is main - adjust if your default branch differs
            git checkout main
            git pull origin main

            echo "=== Install Python dependencies (if changed) ==="
            # prefer correctly spelled requirements; fallback to misspelled file if present
            if [ -f "$APP_DIR/requirements.txt" ]; then
              $VENV_PIP install -r "$APP_DIR/requirements.txt"
            elif [ -f "$APP_DIR/requirment.txt" ]; then
              $VENV_PIP install -r "$APP_DIR/requirment.txt"
            else
              echo "No requirements file found. Skipping pip install."
            fi

            echo "=== Restart PM2 process if exists, otherwise start it ==="
            # Try graceful reload/restart; if PM2 doesn't know the app, start it with gunicorn
            if pm2 list | grep -q "$PM2_NAME"; then
              pm2 reload "$PM2_NAME" || pm2 restart "$PM2_NAME"
            else
              # Start using the existing venv gunicorn binary; adjust module:app if needed (image:app or main:app)
              pm2 start "$GUNICORN_BIN" --name "$PM2_NAME" --interpreter=none -- -w 4 -k uvicorn.workers.UvicornWorker main:app --bind 209.209.40.144:8000
            fi

            echo "=== Save PM2 process list and show status ==="
            pm2 save
            pm2 status
            pm2 logs --lines 50
